### ISSUE TITLE
Firefox Support

### ISSUE THREAD

**Issue by mahnouel** [wingleung/save-page-state#2]
Any plans to support Firefox?

**Comment by wingleung** [comment]
@mahnouel PR submitted, have look :-)

Only problem is Firefox does not support pageCapture which is needed to generate an MHTML file. If we want MHTML then it'll be cleaner if firefox supports pageCapture natively.
You can help upvote the issue here: https://bugzilla.mozilla.org/show_bug.cgi?id=1261339

The firefox add-on is uploaded to https://addons.mozilla.org/en-US/firefox/addon/save-page-state/
